import './globals.css';
import { Cairo, Open_Sans } from 'next/font/google';
import localFont from 'next/font/local';
import ClientProvider from './ClientProvider';
import { Metadata } from 'next';

const cairo = Cairo({
  subsets: ['latin'],
  variable: '--font-cairo',
});

const openSans = Open_Sans({
  subsets: ['latin'],
  variable: '--font-openSans',
});

const myFont = localFont({
  src: './../../public/awesome.ttf',
  variable: '--font-awesome',
});

export const metadata: Metadata = {
  title: 'Weframtech',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <body
        className={`${cairo.variable} ${openSans.variable} ${myFont.variable} bg-[#0D0B21] flex`}
      >
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
